import type { Metadata } from 'next'
import Link from 'next/link'
import { Header } from '@/components/header'
import { Footer } from '@/components/footer'

const url = `${process.env.NEXT_PUBLIC_APP_URL || 'https://www.jacketee.com'}/blog/custom-jacket-design-guide`
const title = 'Design a Bomber, Coach, or Puffer Jacket | Jacketee'
const description = 'Compare bomber, coach, and puffer jacket designs, choose materials and colors, and plan your custom text and artwork.'
export const metadata: Metadata = { title, description, alternates: { canonical: url }, openGraph: { title, description, url, type: 'article' } }
export default function CustomJacketGuide() {
  const schema = { '@context': 'https://schema.org', '@type': 'BlogPosting', headline: title, description, mainEntityOfPage: url, author: { '@type': 'Organization', name: 'Jacketee' } }
  return <div className="flex min-h-screen flex-col"><Header /><main className="mx-auto w-full max-w-3xl flex-1 px-4 py-12">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, '\\u003c') }} />
    <nav aria-label="Breadcrumb" className="text-sm text-muted-foreground"><Link href="/">Home</Link> / <Link href="/blog">Blog</Link> / Custom jacket guide</nav>
    <article className="mt-6 space-y-8 leading-7"><header><h1 className="text-3xl font-bold sm:text-4xl">How to design a bomber, coach, or puffer jacket</h1><p className="mt-5 text-muted-foreground">Choose a silhouette first, then coordinate materials, colors, and artwork. Each template designer starts with its own jacket outline, without choosing a catalog product.</p></header>
      <section aria-labelledby="blog-summary-heading" className="rounded-lg border bg-muted/30 p-5"><h2 id="blog-summary-heading" className="mb-2 text-lg font-semibold">Summary</h2><p>Compare bomber, coach, and puffer silhouettes, coordinate materials and artwork, and review your measurements and price before saving a custom design.</p></section>
      <section><h2 className="mb-3 text-xl font-semibold">Bomber: ribbed trims and utility details</h2><p>The bomber has a gathered waistband, ribbed collar option, and cuffs. Keep the trims plain or add contrasting knit stripes. An optional utility pocket adds detail to the left sleeve. Try a small chest logo and a larger back design, then check the sleeve views before ordering.</p><Link href="/design/bomber" className="mt-3 inline-block font-semibold underline">Design your bomber jacket</Link></section>
      <section><h2 className="mb-3 text-xl font-semibold">Coach: a pointed collar and clean hem</h2><p>A coach jacket uses a point collar and button closure by default. Choose straight or elastic cuffs and a straight or drawcord hem. A simple body color with contrasting text works well for team names and staff jackets. A stand collar, hood, or zipper can change the construction.</p><Link href="/design/coach" className="mt-3 inline-block font-semibold underline">Design your coach jacket</Link></section>
      <section><h2 className="mb-3 text-xl font-semibold">Puffer: padded panels and quilting</h2><p>Compare horizontal and chevron quilting, then choose a padding weight, cuff style, and optional hood. The preview changes the panel spacing to show the padding selection; it does not represent a measured insulation rating. Review text and logos against the quilted panels and contact our team with any specific warmth or construction requirements.</p><Link href="/design/puffer" className="mt-3 inline-block font-semibold underline">Design your puffer jacket</Link></section>
      <section><h2 className="mb-3 text-xl font-semibold">Coordinate colors and materials</h2><p>Choose the body and sleeve materials first, then set the shared sleeve color, collar, cuffs, pockets, and closure colors. Keep artwork readable against the background. Read the <Link href="/materials-colors" className="underline">materials and colors guide</Link> and <Link href="/patches-embroidery" className="underline">patches and embroidery guide</Link> for more planning help. Textures are illustrative.</p></section>
      <section><h2 className="mb-3 text-xl font-semibold">Review your size, design, and price</h2><p>Use the <Link href="/size-guide" className="underline">size guide</Link> and preview all four views. The cotton fleece base is $55 USD, another material adds $10 once per jacket, a hood adds $5, and a zipper adds $2. Artwork and embroidery fees appear in the total. Shipping is calculated at checkout.</p><p className="mt-3">Save design stores your draft in this browser on this device. Download design exports a JSON file with the configuration and four previews. Importing that file is not currently supported.</p></section>
      <section className="rounded-xl border bg-muted/30 p-6"><h2 className="text-xl font-semibold">Prefer a specific product?</h2><p className="mt-3"><Link href="/shop" className="underline">Choose a catalog jacket</Link> and use its customization button to work with that product. You can also <Link href="/design/varsity" className="underline">design a varsity jacket</Link> or <Link href="/contact" className="underline">ask us for help</Link>.</p></section>
    </article>
  </main><Footer /></div>
}
